-- Incremental acknowledgement-receipt schema.
-- Existing public.persons(id) and public.transactions(id) relations are required.
-- All browser-facing access is server mediated; no receipt object is public.

BEGIN;

CREATE SEQUENCE IF NOT EXISTS public.ack_receipt_number_seq
    AS bigint
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

CREATE TABLE IF NOT EXISTS public.payer_portal_access (
    person_id uuid PRIMARY KEY
        REFERENCES public.persons(id) ON DELETE CASCADE,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    pin_hash text NOT NULL,
    credential_version integer NOT NULL DEFAULT 1
        CHECK (credential_version > 0),
    revoked_at timestamptz,
    last_accessed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT payer_portal_access_public_id_key UNIQUE (public_id),
    CONSTRAINT payer_portal_access_pin_hash_check
        CHECK (length(pin_hash) >= 16)
);

CREATE TABLE IF NOT EXISTS public.payer_portal_pin_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portal_person_id uuid NOT NULL
        REFERENCES public.payer_portal_access(person_id) ON DELETE CASCADE,
    network_hash text NOT NULL,
    succeeded boolean NOT NULL DEFAULT false,
    attempted_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT payer_portal_pin_attempts_network_hash_check
        CHECK (length(network_hash) BETWEEN 16 AND 256)
);

CREATE TABLE IF NOT EXISTS public.acknowledgement_receipts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    receipt_number text NOT NULL,
    payer_person_id uuid NOT NULL
        REFERENCES public.persons(id) ON DELETE RESTRICT,
    payer_name_snapshot text NOT NULL,
    receiver_name text NOT NULL,
    amount numeric(14, 2) NOT NULL,
    currency char(3) NOT NULL DEFAULT 'PHP',
    payment_date date NOT NULL,
    notes text,
    revision_number integer NOT NULL DEFAULT 1,
    published_at timestamptz,
    payer_confirmed_at timestamptz,
    receiver_confirmed_at timestamptz,
    completed_at timestamptz,
    is_completed boolean GENERATED ALWAYS AS (completed_at IS NOT NULL) STORED,
    voided_at timestamptz,
    void_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT acknowledgement_receipts_receipt_number_key
        UNIQUE (receipt_number),
    CONSTRAINT acknowledgement_receipts_receipt_number_check
        CHECK (receipt_number ~ '^AR-[0-9]{4}-[0-9]{6}$'),
    CONSTRAINT acknowledgement_receipts_payer_name_check
        CHECK (
            length(btrim(payer_name_snapshot)) BETWEEN 1 AND 200
            AND payer_name_snapshot = btrim(payer_name_snapshot)
        ),
    CONSTRAINT acknowledgement_receipts_receiver_name_check
        CHECK (
            length(btrim(receiver_name)) BETWEEN 1 AND 200
            AND receiver_name = btrim(receiver_name)
        ),
    CONSTRAINT acknowledgement_receipts_amount_check
        CHECK (amount > 0),
    CONSTRAINT acknowledgement_receipts_currency_check
        CHECK (currency::text ~ '^[A-Z]{3}$'),
    CONSTRAINT acknowledgement_receipts_notes_check
        CHECK (notes IS NULL OR length(notes) <= 5000),
    CONSTRAINT acknowledgement_receipts_revision_check
        CHECK (revision_number > 0),
    CONSTRAINT acknowledgement_receipts_confirmation_check
        CHECK (
            completed_at IS NULL
            OR (
                published_at IS NOT NULL
                AND payer_confirmed_at IS NOT NULL
                AND receiver_confirmed_at IS NOT NULL
            )
        ),
    CONSTRAINT acknowledgement_receipts_published_confirmation_check
        CHECK (
            published_at IS NOT NULL
            OR (
                payer_confirmed_at IS NULL
                AND receiver_confirmed_at IS NULL
                AND completed_at IS NULL
            )
        ),
    CONSTRAINT acknowledgement_receipts_void_check
        CHECK (
            (voided_at IS NULL AND void_reason IS NULL)
            OR (
                voided_at IS NOT NULL
                AND void_reason IS NOT NULL
                AND length(btrim(void_reason)) BETWEEN 1 AND 1000
            )
        )
);

CREATE TABLE IF NOT EXISTS public.acknowledgement_receipt_transactions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    receipt_id uuid NOT NULL
        REFERENCES public.acknowledgement_receipts(id) ON DELETE CASCADE,
    transaction_id uuid
        REFERENCES public.transactions(id) ON DELETE SET NULL,
    transaction_date_snapshot date NOT NULL,
    description_snapshot text NOT NULL,
    amount_snapshot numeric(14, 2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT acknowledgement_receipt_transactions_description_check
        CHECK (length(btrim(description_snapshot)) > 0)
);

CREATE TABLE IF NOT EXISTS public.acknowledgement_receipt_files (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    receipt_id uuid NOT NULL
        REFERENCES public.acknowledgement_receipts(id) ON DELETE CASCADE,
    storage_path text NOT NULL,
    original_filename text NOT NULL,
    content_type text NOT NULL,
    size_bytes bigint NOT NULL,
    uploader_role text NOT NULL,
    removed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT acknowledgement_receipt_files_storage_path_key
        UNIQUE (storage_path),
    CONSTRAINT acknowledgement_receipt_files_storage_path_check
        CHECK (length(btrim(storage_path)) BETWEEN 1 AND 1024),
    CONSTRAINT acknowledgement_receipt_files_filename_check
        CHECK (length(btrim(original_filename)) BETWEEN 1 AND 255),
    CONSTRAINT acknowledgement_receipt_files_content_type_check
        CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp')),
    CONSTRAINT acknowledgement_receipt_files_size_check
        CHECK (size_bytes > 0 AND size_bytes <= 10 * 1024 * 1024),
    CONSTRAINT acknowledgement_receipt_files_uploader_role_check
        CHECK (uploader_role IN ('payer', 'receiver'))
);

CREATE TABLE IF NOT EXISTS public.acknowledgement_receipt_revisions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    receipt_id uuid NOT NULL
        REFERENCES public.acknowledgement_receipts(id) ON DELETE CASCADE,
    revision_number integer NOT NULL,
    snapshot jsonb NOT NULL,
    change_reason text NOT NULL,
    changed_by_role text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT acknowledgement_receipt_revisions_receipt_revision_key
        UNIQUE (receipt_id, revision_number),
    CONSTRAINT acknowledgement_receipt_revisions_revision_check
        CHECK (revision_number > 0),
    CONSTRAINT acknowledgement_receipt_revisions_snapshot_check
        CHECK (jsonb_typeof(snapshot) = 'object'),
    CONSTRAINT acknowledgement_receipt_revisions_reason_check
        CHECK (length(btrim(change_reason)) BETWEEN 1 AND 1000),
    CONSTRAINT acknowledgement_receipt_revisions_role_check
        CHECK (changed_by_role IN ('payer', 'receiver', 'system'))
);

CREATE TABLE IF NOT EXISTS public.acknowledgement_receipt_events (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    receipt_id uuid
        REFERENCES public.acknowledgement_receipts(id) ON DELETE CASCADE,
    portal_person_id uuid
        REFERENCES public.payer_portal_access(person_id) ON DELETE CASCADE,
    event_type text NOT NULL,
    actor_role text NOT NULL,
    revision_number integer,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT acknowledgement_receipt_events_type_check
        CHECK (length(btrim(event_type)) BETWEEN 1 AND 100),
    CONSTRAINT acknowledgement_receipt_events_actor_role_check
        CHECK (actor_role IN ('payer', 'receiver', 'system')),
    CONSTRAINT acknowledgement_receipt_events_subject_check
        CHECK (
            (
                receipt_id IS NOT NULL
                AND portal_person_id IS NULL
                AND revision_number IS NOT NULL
                AND revision_number > 0
            )
            OR (
                receipt_id IS NULL
                AND portal_person_id IS NOT NULL
                AND revision_number IS NULL
            )
        ),
    CONSTRAINT acknowledgement_receipt_events_details_check
        CHECK (jsonb_typeof(details) = 'object')
);

CREATE INDEX IF NOT EXISTS payer_portal_pin_attempts_portal_idx
    ON public.payer_portal_pin_attempts (portal_person_id);
CREATE INDEX IF NOT EXISTS payer_portal_pin_attempts_rate_limit_idx
    ON public.payer_portal_pin_attempts (
        portal_person_id,
        network_hash,
        attempted_at DESC
    );
CREATE INDEX IF NOT EXISTS acknowledgement_receipts_payer_idx
    ON public.acknowledgement_receipts (payer_person_id);
CREATE INDEX IF NOT EXISTS acknowledgement_receipts_payment_date_idx
    ON public.acknowledgement_receipts (payment_date DESC);
CREATE INDEX IF NOT EXISTS acknowledgement_receipt_transactions_receipt_idx
    ON public.acknowledgement_receipt_transactions (receipt_id);
CREATE INDEX IF NOT EXISTS acknowledgement_receipt_transactions_transaction_idx
    ON public.acknowledgement_receipt_transactions (transaction_id);
CREATE UNIQUE INDEX IF NOT EXISTS acknowledgement_receipt_transactions_live_key
    ON public.acknowledgement_receipt_transactions (receipt_id, transaction_id)
    WHERE transaction_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS acknowledgement_receipt_files_receipt_idx
    ON public.acknowledgement_receipt_files (receipt_id);
CREATE INDEX IF NOT EXISTS acknowledgement_receipt_files_active_idx
    ON public.acknowledgement_receipt_files (receipt_id, created_at)
    WHERE removed_at IS NULL;
CREATE INDEX IF NOT EXISTS acknowledgement_receipt_revisions_receipt_idx
    ON public.acknowledgement_receipt_revisions (receipt_id);
CREATE INDEX IF NOT EXISTS acknowledgement_receipt_events_receipt_idx
    ON public.acknowledgement_receipt_events (receipt_id);
CREATE INDEX IF NOT EXISTS acknowledgement_receipt_events_portal_idx
    ON public.acknowledgement_receipt_events (portal_person_id);

INSERT INTO storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
VALUES (
    'acknowledgement-proofs',
    'acknowledgement-proofs',
    false,
    10 * 1024 * 1024,
    ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO UPDATE
SET
    public = false,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE OR REPLACE FUNCTION public.ack_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
BEGIN
    NEW.updated_at := clock_timestamp();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.ack_reject_append_only()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
BEGIN
    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME
        USING ERRCODE = '55000';
END;
$$;

CREATE OR REPLACE FUNCTION public.ack_enforce_active_file_limit()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_active_count integer;
BEGIN
    IF (
        TG_OP = 'UPDATE'
        AND NEW.receipt_id IS DISTINCT FROM OLD.receipt_id
    ) THEN
        RAISE EXCEPTION 'proof receipt_id is immutable'
            USING ERRCODE = '55000';
    END IF;

    IF NEW.removed_at IS NOT NULL THEN
        RETURN NEW;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF OLD.removed_at IS NULL THEN
            RETURN NEW;
        END IF;
    END IF;

    PERFORM 1
    FROM public.acknowledgement_receipts
    WHERE id = NEW.receipt_id
    FOR UPDATE;

    SELECT count(*)
    INTO v_active_count
    FROM public.acknowledgement_receipt_files
    WHERE receipt_id = NEW.receipt_id
      AND removed_at IS NULL;

    IF v_active_count >= 5 THEN
        RAISE EXCEPTION 'a receipt may have at most five active files'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS payer_portal_access_touch_updated_at
    ON public.payer_portal_access;
CREATE TRIGGER payer_portal_access_touch_updated_at
BEFORE UPDATE ON public.payer_portal_access
FOR EACH ROW
EXECUTE FUNCTION public.ack_touch_updated_at();

DROP TRIGGER IF EXISTS acknowledgement_receipts_touch_updated_at
    ON public.acknowledgement_receipts;
CREATE TRIGGER acknowledgement_receipts_touch_updated_at
BEFORE UPDATE ON public.acknowledgement_receipts
FOR EACH ROW
EXECUTE FUNCTION public.ack_touch_updated_at();

DROP TRIGGER IF EXISTS acknowledgement_receipt_files_limit
    ON public.acknowledgement_receipt_files;
CREATE TRIGGER acknowledgement_receipt_files_limit
BEFORE INSERT OR UPDATE OF receipt_id, removed_at
ON public.acknowledgement_receipt_files
FOR EACH ROW
EXECUTE FUNCTION public.ack_enforce_active_file_limit();

DROP TRIGGER IF EXISTS acknowledgement_receipt_revisions_append_only
    ON public.acknowledgement_receipt_revisions;
CREATE TRIGGER acknowledgement_receipt_revisions_append_only
BEFORE UPDATE OR DELETE ON public.acknowledgement_receipt_revisions
FOR EACH ROW
EXECUTE FUNCTION public.ack_reject_append_only();

DROP TRIGGER IF EXISTS acknowledgement_receipt_events_append_only
    ON public.acknowledgement_receipt_events;
CREATE TRIGGER acknowledgement_receipt_events_append_only
BEFORE UPDATE OR DELETE ON public.acknowledgement_receipt_events
FOR EACH ROW
EXECUTE FUNCTION public.ack_reject_append_only();

CREATE OR REPLACE FUNCTION public.ack_snapshot_receipt(
    p_receipt_id uuid,
    p_change_reason text,
    p_changed_by_role text
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_receipt public.acknowledgement_receipts%ROWTYPE;
    v_snapshot jsonb;
    v_status text;
BEGIN
    IF p_changed_by_role NOT IN ('payer', 'receiver', 'system') THEN
        RAISE EXCEPTION 'invalid receipt actor role'
            USING ERRCODE = '22023';
    END IF;

    SELECT *
    INTO v_receipt
    FROM public.acknowledgement_receipts
    WHERE id = p_receipt_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    v_status := CASE
        WHEN v_receipt.voided_at IS NOT NULL THEN 'voided'
        WHEN v_receipt.published_at IS NULL THEN 'draft'
        WHEN (
            v_receipt.completed_at IS NOT NULL
            AND v_receipt.payer_confirmed_at IS NOT NULL
            AND v_receipt.receiver_confirmed_at IS NOT NULL
        ) THEN 'completed'
        WHEN (
            v_receipt.payer_confirmed_at IS NULL
            AND v_receipt.receiver_confirmed_at IS NOT NULL
        ) THEN 'awaiting_payer'
        WHEN (
            v_receipt.payer_confirmed_at IS NOT NULL
            AND v_receipt.receiver_confirmed_at IS NULL
        ) THEN 'awaiting_receiver'
        ELSE 'awaiting_both'
    END;

    v_snapshot := jsonb_build_object(
        'receipt',
        jsonb_build_object(
            'id', v_receipt.id,
            'receiptNumber', v_receipt.receipt_number,
            'payerPersonId', v_receipt.payer_person_id,
            'payerName', v_receipt.payer_name_snapshot,
            'receiverName', v_receipt.receiver_name,
            'amount', v_receipt.amount,
            'currency', btrim(v_receipt.currency::text),
            'paymentDate', v_receipt.payment_date,
            'notes', v_receipt.notes,
            'revisionNumber', v_receipt.revision_number,
            'publishedAt', v_receipt.published_at,
            'payerConfirmedAt', v_receipt.payer_confirmed_at,
            'receiverConfirmedAt', v_receipt.receiver_confirmed_at,
            'completedAt', v_receipt.completed_at,
            'isCompleted', v_receipt.is_completed,
            'voidedAt', v_receipt.voided_at,
            'voidReason', v_receipt.void_reason,
            'status', v_status,
            'createdAt', v_receipt.created_at,
            'updatedAt', v_receipt.updated_at
        ),
        'transactions',
        COALESCE(
            (
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'id', receipt_transaction.id,
                        'transactionId', receipt_transaction.transaction_id,
                        'transactionDate',
                            receipt_transaction.transaction_date_snapshot,
                        'description',
                            receipt_transaction.description_snapshot,
                        'amount', receipt_transaction.amount_snapshot,
                        'createdAt', receipt_transaction.created_at
                    )
                    ORDER BY
                        receipt_transaction.created_at,
                        receipt_transaction.id
                )
                FROM public.acknowledgement_receipt_transactions receipt_transaction
                WHERE receipt_transaction.receipt_id = p_receipt_id
            ),
            '[]'::jsonb
        ),
        'proofs',
        COALESCE(
            (
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'id', receipt_file.id,
                        'originalFilename', receipt_file.original_filename,
                        'contentType', receipt_file.content_type,
                        'sizeBytes', receipt_file.size_bytes,
                        'uploaderRole', receipt_file.uploader_role,
                        'removedAt', receipt_file.removed_at,
                        'createdAt', receipt_file.created_at
                    )
                    ORDER BY receipt_file.created_at, receipt_file.id
                )
                FROM public.acknowledgement_receipt_files receipt_file
                WHERE receipt_file.receipt_id = p_receipt_id
            ),
            '[]'::jsonb
        )
    );

    INSERT INTO public.acknowledgement_receipt_revisions (
        receipt_id,
        revision_number,
        snapshot,
        change_reason,
        changed_by_role
    )
    VALUES (
        p_receipt_id,
        v_receipt.revision_number,
        v_snapshot,
        p_change_reason,
        p_changed_by_role
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.ack_create_receipt(
    p_payer_person_id uuid,
    p_receiver_name text,
    p_amount numeric,
    p_currency text,
    p_payment_date date,
    p_notes text,
    p_transaction_ids uuid[]
)
RETURNS public.acknowledgement_receipts
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_receipt public.acknowledgement_receipts%ROWTYPE;
    v_payer_name text;
    v_sequence_value bigint;
    v_inserted_count integer;
    v_transaction_ids uuid[] := COALESCE(p_transaction_ids, ARRAY[]::uuid[]);
BEGIN
    IF (
        p_amount <= 0
        OR p_amount > 999999999999.99
        OR p_amount <> round(p_amount, 2)
    ) THEN
        RAISE EXCEPTION 'receipt amount must fit positive numeric(14,2)'
            USING ERRCODE = '22023';
    END IF;

    IF p_currency !~ '^[A-Z]{3}$' THEN
        RAISE EXCEPTION 'currency must be three uppercase letters'
            USING ERRCODE = '22023';
    END IF;

    IF cardinality(v_transaction_ids) <> (
        SELECT count(DISTINCT input_id)
        FROM unnest(v_transaction_ids) AS input_transaction(input_id)
    ) THEN
        RAISE EXCEPTION 'transaction ids must be unique'
            USING ERRCODE = '22023';
    END IF;

    SELECT btrim(name)
    INTO v_payer_name
    FROM public.persons
    WHERE id = p_payer_person_id;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    v_sequence_value := nextval('public.ack_receipt_number_seq');
    IF v_sequence_value > 999999 THEN
        RAISE EXCEPTION 'acknowledgement receipt sequence exhausted'
            USING ERRCODE = '54000';
    END IF;

    INSERT INTO public.acknowledgement_receipts (
        receipt_number,
        payer_person_id,
        payer_name_snapshot,
        receiver_name,
        amount,
        currency,
        payment_date,
        notes
    )
    VALUES (
        format(
            'AR-%s-%s',
            to_char(clock_timestamp() AT TIME ZONE 'Asia/Manila', 'YYYY'),
            lpad(v_sequence_value::text, 6, '0')
        ),
        p_payer_person_id,
        v_payer_name,
        btrim(p_receiver_name),
        p_amount,
        p_currency,
        p_payment_date,
        p_notes
    )
    RETURNING * INTO v_receipt;

    INSERT INTO public.acknowledgement_receipt_transactions (
        receipt_id,
        transaction_id,
        transaction_date_snapshot,
        description_snapshot,
        amount_snapshot
    )
    SELECT
        v_receipt.id,
        transaction_row.id,
        transaction_row.date,
        transaction_row.description,
        transaction_row.amount
    FROM public.transactions transaction_row
    WHERE transaction_row.id = ANY(v_transaction_ids)
      AND transaction_row.person_id = p_payer_person_id;

    GET DIAGNOSTICS v_inserted_count = ROW_COUNT;
    IF v_inserted_count <> cardinality(v_transaction_ids) THEN
        RAISE EXCEPTION 'all transactions must exist and belong to the payer'
            USING ERRCODE = '22023';
    END IF;

    INSERT INTO public.acknowledgement_receipt_events (
        receipt_id,
        event_type,
        actor_role,
        revision_number
    )
    VALUES (v_receipt.id, 'created', 'receiver', v_receipt.revision_number);

    RETURN v_receipt;
END;
$$;

CREATE OR REPLACE FUNCTION public.ack_update_receipt(
    p_receipt_id uuid,
    p_expected_revision integer,
    p_payer_person_id uuid,
    p_receiver_name text,
    p_amount numeric,
    p_currency text,
    p_payment_date date,
    p_notes text,
    p_transaction_ids uuid[]
)
RETURNS public.acknowledgement_receipts
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_receipt public.acknowledgement_receipts%ROWTYPE;
    v_payer_name text;
    v_inserted_count integer;
    v_had_confirmation boolean;
    v_is_unchanged boolean;
    v_transaction_ids uuid[] := COALESCE(p_transaction_ids, ARRAY[]::uuid[]);
BEGIN
    SELECT *
    INTO v_receipt
    FROM public.acknowledgement_receipts
    WHERE id = p_receipt_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    IF v_receipt.revision_number <> p_expected_revision THEN
        RAISE EXCEPTION 'acknowledgement receipt revision conflict'
            USING
                ERRCODE = '40001',
                DETAIL = format(
                    'expected revision %s, current revision %s',
                    p_expected_revision,
                    v_receipt.revision_number
                );
    END IF;

    IF v_receipt.voided_at IS NOT NULL THEN
        RAISE EXCEPTION 'voided receipts cannot be edited'
            USING ERRCODE = '55000';
    END IF;

    IF (
        p_amount <= 0
        OR p_amount > 999999999999.99
        OR p_amount <> round(p_amount, 2)
    ) THEN
        RAISE EXCEPTION 'receipt amount must fit positive numeric(14,2)'
            USING ERRCODE = '22023';
    END IF;

    IF p_currency !~ '^[A-Z]{3}$' THEN
        RAISE EXCEPTION 'currency must be three uppercase letters'
            USING ERRCODE = '22023';
    END IF;

    IF cardinality(v_transaction_ids) <> (
        SELECT count(DISTINCT input_id)
        FROM unnest(v_transaction_ids) AS input_transaction(input_id)
    ) THEN
        RAISE EXCEPTION 'transaction ids must be unique'
            USING ERRCODE = '22023';
    END IF;

    SELECT btrim(name)
    INTO v_payer_name
    FROM public.persons
    WHERE id = p_payer_person_id;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    v_is_unchanged := (
        v_receipt.payer_person_id IS NOT DISTINCT FROM p_payer_person_id
        AND v_receipt.payer_name_snapshot IS NOT DISTINCT FROM v_payer_name
        AND v_receipt.receiver_name IS NOT DISTINCT FROM btrim(p_receiver_name)
        AND v_receipt.amount IS NOT DISTINCT FROM p_amount
        AND btrim(v_receipt.currency::text) IS NOT DISTINCT FROM p_currency
        AND v_receipt.payment_date IS NOT DISTINCT FROM p_payment_date
        AND v_receipt.notes IS NOT DISTINCT FROM p_notes
        AND NOT EXISTS (
            SELECT receipt_transaction.transaction_id
            FROM public.acknowledgement_receipt_transactions receipt_transaction
            WHERE receipt_transaction.receipt_id = p_receipt_id
            EXCEPT
            SELECT input_transaction.input_id
            FROM unnest(v_transaction_ids) AS input_transaction(input_id)
        )
        AND NOT EXISTS (
            SELECT input_transaction.input_id
            FROM unnest(v_transaction_ids) AS input_transaction(input_id)
            EXCEPT
            SELECT receipt_transaction.transaction_id
            FROM public.acknowledgement_receipt_transactions receipt_transaction
            WHERE receipt_transaction.receipt_id = p_receipt_id
        )
    );

    IF v_is_unchanged THEN
        RETURN v_receipt;
    END IF;

    v_had_confirmation := (
        v_receipt.payer_confirmed_at IS NOT NULL
        OR v_receipt.receiver_confirmed_at IS NOT NULL
        OR v_receipt.completed_at IS NOT NULL
    );

    PERFORM public.ack_snapshot_receipt(
        p_receipt_id,
        'receipt content or transaction references updated',
        'receiver'
    );

    DELETE FROM public.acknowledgement_receipt_transactions
    WHERE receipt_id = p_receipt_id;

    INSERT INTO public.acknowledgement_receipt_transactions (
        receipt_id,
        transaction_id,
        transaction_date_snapshot,
        description_snapshot,
        amount_snapshot
    )
    SELECT
        p_receipt_id,
        transaction_row.id,
        transaction_row.date,
        transaction_row.description,
        transaction_row.amount
    FROM public.transactions transaction_row
    WHERE transaction_row.id = ANY(v_transaction_ids)
      AND transaction_row.person_id = p_payer_person_id;

    GET DIAGNOSTICS v_inserted_count = ROW_COUNT;
    IF v_inserted_count <> cardinality(v_transaction_ids) THEN
        RAISE EXCEPTION 'all transactions must exist and belong to the payer'
            USING ERRCODE = '22023';
    END IF;

    UPDATE public.acknowledgement_receipts
    SET
        payer_person_id = p_payer_person_id,
        payer_name_snapshot = v_payer_name,
        receiver_name = btrim(p_receiver_name),
        amount = p_amount,
        currency = p_currency,
        payment_date = p_payment_date,
        notes = p_notes,
        revision_number = revision_number + 1,
        payer_confirmed_at = NULL,
        receiver_confirmed_at = NULL,
        completed_at = NULL
    WHERE id = p_receipt_id
    RETURNING * INTO v_receipt;

    INSERT INTO public.acknowledgement_receipt_events (
        receipt_id,
        event_type,
        actor_role,
        revision_number
    )
    VALUES (
        p_receipt_id,
        'receipt_updated',
        'receiver',
        v_receipt.revision_number
    );

    IF v_had_confirmation THEN
        INSERT INTO public.acknowledgement_receipt_events (
            receipt_id,
            event_type,
            actor_role,
            revision_number,
            details
        )
        VALUES (
            p_receipt_id,
            'confirmation_reset',
            'receiver',
            v_receipt.revision_number,
            '{"reason":"receipt_updated"}'::jsonb
        );
    END IF;

    RETURN v_receipt;
END;
$$;

CREATE OR REPLACE FUNCTION public.ack_publish_receipt(
    p_receipt_id uuid,
    p_expected_revision integer
)
RETURNS public.acknowledgement_receipts
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_receipt public.acknowledgement_receipts%ROWTYPE;
BEGIN
    SELECT *
    INTO v_receipt
    FROM public.acknowledgement_receipts
    WHERE id = p_receipt_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    IF v_receipt.revision_number <> p_expected_revision THEN
        RAISE EXCEPTION 'acknowledgement receipt revision conflict'
            USING ERRCODE = '40001';
    END IF;

    IF v_receipt.voided_at IS NOT NULL THEN
        RAISE EXCEPTION 'voided receipts cannot be published'
            USING ERRCODE = '55000';
    END IF;

    IF v_receipt.published_at IS NOT NULL THEN
        RETURN v_receipt;
    END IF;

    UPDATE public.acknowledgement_receipts
    SET published_at = clock_timestamp()
    WHERE id = p_receipt_id
    RETURNING * INTO v_receipt;

    INSERT INTO public.acknowledgement_receipt_events (
        receipt_id,
        event_type,
        actor_role,
        revision_number
    )
    VALUES (p_receipt_id, 'published', 'receiver', v_receipt.revision_number);

    RETURN v_receipt;
END;
$$;

CREATE OR REPLACE FUNCTION public.ack_confirm_receipt(
    p_receipt_id uuid,
    p_expected_revision integer,
    p_role text
)
RETURNS public.acknowledgement_receipts
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_receipt public.acknowledgement_receipts%ROWTYPE;
    v_confirmed_at timestamptz := clock_timestamp();
    v_became_completed boolean := false;
BEGIN
    IF p_role NOT IN ('payer', 'receiver') THEN
        RAISE EXCEPTION 'confirmation role must be payer or receiver'
            USING ERRCODE = '22023';
    END IF;

    SELECT *
    INTO v_receipt
    FROM public.acknowledgement_receipts
    WHERE id = p_receipt_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    IF v_receipt.revision_number <> p_expected_revision THEN
        RAISE EXCEPTION 'acknowledgement receipt revision conflict'
            USING ERRCODE = '40001';
    END IF;

    IF v_receipt.published_at IS NULL THEN
        RAISE EXCEPTION 'draft receipts cannot be confirmed'
            USING ERRCODE = '55000';
    END IF;

    IF v_receipt.voided_at IS NOT NULL THEN
        RAISE EXCEPTION 'voided receipts cannot be confirmed'
            USING ERRCODE = '55000';
    END IF;

    IF (
        p_role = 'payer'
        AND v_receipt.payer_confirmed_at IS NOT NULL
    ) OR (
        p_role = 'receiver'
        AND v_receipt.receiver_confirmed_at IS NOT NULL
    ) THEN
        RETURN v_receipt;
    END IF;

    UPDATE public.acknowledgement_receipts
    SET
        payer_confirmed_at = CASE
            WHEN p_role = 'payer' THEN v_confirmed_at
            ELSE payer_confirmed_at
        END,
        receiver_confirmed_at = CASE
            WHEN p_role = 'receiver' THEN v_confirmed_at
            ELSE receiver_confirmed_at
        END
    WHERE id = p_receipt_id
    RETURNING * INTO v_receipt;

    IF (
        v_receipt.payer_confirmed_at IS NOT NULL
        AND v_receipt.receiver_confirmed_at IS NOT NULL
        AND v_receipt.completed_at IS NULL
    ) THEN
        UPDATE public.acknowledgement_receipts
        SET completed_at = v_confirmed_at
        WHERE id = p_receipt_id
        RETURNING * INTO v_receipt;
        v_became_completed := true;
    END IF;

    INSERT INTO public.acknowledgement_receipt_events (
        receipt_id,
        event_type,
        actor_role,
        revision_number
    )
    VALUES (
        p_receipt_id,
        p_role || '_confirmed',
        p_role,
        v_receipt.revision_number
    );

    IF v_became_completed THEN
        INSERT INTO public.acknowledgement_receipt_events (
            receipt_id,
            event_type,
            actor_role,
            revision_number
        )
        VALUES (
            p_receipt_id,
            'completed',
            p_role,
            v_receipt.revision_number
        );
    END IF;

    RETURN v_receipt;
END;
$$;

CREATE OR REPLACE FUNCTION public.ack_void_receipt(
    p_receipt_id uuid,
    p_expected_revision integer,
    p_reason text
)
RETURNS public.acknowledgement_receipts
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_receipt public.acknowledgement_receipts%ROWTYPE;
    v_reason text := btrim(p_reason);
BEGIN
    IF v_reason IS NULL OR length(v_reason) NOT BETWEEN 1 AND 1000 THEN
        RAISE EXCEPTION 'void reason must contain 1 to 1000 characters'
            USING ERRCODE = '22023';
    END IF;

    SELECT *
    INTO v_receipt
    FROM public.acknowledgement_receipts
    WHERE id = p_receipt_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    IF v_receipt.revision_number <> p_expected_revision THEN
        RAISE EXCEPTION 'acknowledgement receipt revision conflict'
            USING ERRCODE = '40001';
    END IF;

    IF v_receipt.voided_at IS NOT NULL THEN
        IF v_receipt.void_reason = v_reason THEN
            RETURN v_receipt;
        END IF;

        RAISE EXCEPTION 'receipt is already voided'
            USING ERRCODE = '55000';
    END IF;

    UPDATE public.acknowledgement_receipts
    SET
        voided_at = clock_timestamp(),
        void_reason = v_reason
    WHERE id = p_receipt_id
    RETURNING * INTO v_receipt;

    INSERT INTO public.acknowledgement_receipt_events (
        receipt_id,
        event_type,
        actor_role,
        revision_number,
        details
    )
    VALUES (
        p_receipt_id,
        'voided',
        'receiver',
        v_receipt.revision_number,
        jsonb_build_object('reason', v_reason)
    );

    RETURN v_receipt;
END;
$$;

CREATE OR REPLACE FUNCTION public.ack_register_file(
    p_receipt_id uuid,
    p_expected_revision integer,
    p_storage_path text,
    p_original_filename text,
    p_content_type text,
    p_size_bytes bigint,
    p_uploader_role text
)
RETURNS public.acknowledgement_receipts
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_receipt public.acknowledgement_receipts%ROWTYPE;
    v_file_id uuid;
    v_had_confirmation boolean;
BEGIN
    IF p_uploader_role NOT IN ('payer', 'receiver') THEN
        RAISE EXCEPTION 'uploader role must be payer or receiver'
            USING ERRCODE = '22023';
    END IF;

    SELECT *
    INTO v_receipt
    FROM public.acknowledgement_receipts
    WHERE id = p_receipt_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    IF v_receipt.revision_number <> p_expected_revision THEN
        RAISE EXCEPTION 'acknowledgement receipt revision conflict'
            USING ERRCODE = '40001';
    END IF;

    IF v_receipt.voided_at IS NOT NULL THEN
        RAISE EXCEPTION 'voided receipts cannot accept files'
            USING ERRCODE = '55000';
    END IF;

    IF p_uploader_role = 'payer' AND v_receipt.published_at IS NULL THEN
        RAISE EXCEPTION 'payers cannot add files to draft receipts'
            USING ERRCODE = '55000';
    END IF;

    IF p_uploader_role = 'payer' AND v_receipt.completed_at IS NOT NULL THEN
        RAISE EXCEPTION 'completed receipts are read-only for payers'
            USING ERRCODE = '55000';
    END IF;

    v_had_confirmation := (
        v_receipt.payer_confirmed_at IS NOT NULL
        OR v_receipt.receiver_confirmed_at IS NOT NULL
        OR v_receipt.completed_at IS NOT NULL
    );

    PERFORM public.ack_snapshot_receipt(
        p_receipt_id,
        'proof file added',
        p_uploader_role
    );

    INSERT INTO public.acknowledgement_receipt_files (
        receipt_id,
        storage_path,
        original_filename,
        content_type,
        size_bytes,
        uploader_role
    )
    VALUES (
        p_receipt_id,
        btrim(p_storage_path),
        btrim(p_original_filename),
        p_content_type,
        p_size_bytes,
        p_uploader_role
    )
    RETURNING id INTO v_file_id;

    UPDATE public.acknowledgement_receipts
    SET
        revision_number = revision_number + 1,
        payer_confirmed_at = NULL,
        receiver_confirmed_at = NULL,
        completed_at = NULL
    WHERE id = p_receipt_id
    RETURNING * INTO v_receipt;

    INSERT INTO public.acknowledgement_receipt_events (
        receipt_id,
        event_type,
        actor_role,
        revision_number,
        details
    )
    VALUES (
        p_receipt_id,
        'proof_added',
        p_uploader_role,
        v_receipt.revision_number,
        jsonb_build_object('file_id', v_file_id)
    );

    IF v_had_confirmation THEN
        INSERT INTO public.acknowledgement_receipt_events (
            receipt_id,
            event_type,
            actor_role,
            revision_number,
            details
        )
        VALUES (
            p_receipt_id,
            'confirmation_reset',
            p_uploader_role,
            v_receipt.revision_number,
            '{"reason":"proof_added"}'::jsonb
        );
    END IF;

    RETURN v_receipt;
END;
$$;

CREATE OR REPLACE FUNCTION public.ack_remove_file(
    p_receipt_id uuid,
    p_expected_revision integer,
    p_file_id uuid,
    p_actor_role text
)
RETURNS public.acknowledgement_receipts
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_receipt public.acknowledgement_receipts%ROWTYPE;
    v_file public.acknowledgement_receipt_files%ROWTYPE;
    v_had_confirmation boolean;
BEGIN
    IF p_actor_role NOT IN ('payer', 'receiver') THEN
        RAISE EXCEPTION 'actor role must be payer or receiver'
            USING ERRCODE = '22023';
    END IF;

    SELECT *
    INTO v_receipt
    FROM public.acknowledgement_receipts
    WHERE id = p_receipt_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    IF v_receipt.revision_number <> p_expected_revision THEN
        RAISE EXCEPTION 'acknowledgement receipt revision conflict'
            USING ERRCODE = '40001';
    END IF;

    IF v_receipt.voided_at IS NOT NULL THEN
        RAISE EXCEPTION 'voided receipts cannot remove files'
            USING ERRCODE = '55000';
    END IF;

    IF p_actor_role = 'payer' AND v_receipt.completed_at IS NOT NULL THEN
        RAISE EXCEPTION 'completed receipts are read-only for payers'
            USING ERRCODE = '55000';
    END IF;

    SELECT *
    INTO v_file
    FROM public.acknowledgement_receipt_files
    WHERE id = p_file_id
      AND receipt_id = p_receipt_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    IF v_file.removed_at IS NOT NULL THEN
        RETURN v_receipt;
    END IF;

    IF p_actor_role = 'payer' AND v_file.uploader_role <> 'payer' THEN
        RAISE EXCEPTION 'payers may only remove files they uploaded'
            USING ERRCODE = '42501';
    END IF;

    v_had_confirmation := (
        v_receipt.payer_confirmed_at IS NOT NULL
        OR v_receipt.receiver_confirmed_at IS NOT NULL
        OR v_receipt.completed_at IS NOT NULL
    );

    PERFORM public.ack_snapshot_receipt(
        p_receipt_id,
        'proof file removed',
        p_actor_role
    );

    UPDATE public.acknowledgement_receipt_files
    SET removed_at = clock_timestamp()
    WHERE id = p_file_id;

    UPDATE public.acknowledgement_receipts
    SET
        revision_number = revision_number + 1,
        payer_confirmed_at = NULL,
        receiver_confirmed_at = NULL,
        completed_at = NULL
    WHERE id = p_receipt_id
    RETURNING * INTO v_receipt;

    INSERT INTO public.acknowledgement_receipt_events (
        receipt_id,
        event_type,
        actor_role,
        revision_number,
        details
    )
    VALUES (
        p_receipt_id,
        'proof_removed',
        p_actor_role,
        v_receipt.revision_number,
        jsonb_build_object('file_id', p_file_id)
    );

    IF v_had_confirmation THEN
        INSERT INTO public.acknowledgement_receipt_events (
            receipt_id,
            event_type,
            actor_role,
            revision_number,
            details
        )
        VALUES (
            p_receipt_id,
            'confirmation_reset',
            p_actor_role,
            v_receipt.revision_number,
            '{"reason":"proof_removed"}'::jsonb
        );
    END IF;

    RETURN v_receipt;
END;
$$;

CREATE OR REPLACE FUNCTION public.ack_set_transaction_paid(
    p_transaction_id uuid,
    p_paid boolean,
    p_receipt_id uuid,
    p_expected_revision integer
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_transaction public.transactions%ROWTYPE;
    v_receipt public.acknowledgement_receipts%ROWTYPE;
    v_had_confirmation boolean;
BEGIN
    IF p_receipt_id IS NULL THEN
        SELECT *
        INTO v_transaction
        FROM public.transactions
        WHERE id = p_transaction_id
        FOR UPDATE;

        IF NOT FOUND THEN
            RAISE no_data_found;
        END IF;

        UPDATE public.transactions
        SET paid = p_paid
        WHERE id = p_transaction_id;

        RETURN jsonb_build_object(
            'transaction_id', p_transaction_id,
            'paid', p_paid,
            'receipt_id', NULL,
            'receipt_revision', NULL
        );
    END IF;

    IF NOT p_paid THEN
        RAISE EXCEPTION 'a receipt can only be linked while marking paid'
            USING ERRCODE = '22023';
    END IF;

    IF p_expected_revision IS NULL THEN
        RAISE EXCEPTION 'expected revision is required when linking a receipt'
            USING ERRCODE = '22023';
    END IF;

    SELECT *
    INTO v_receipt
    FROM public.acknowledgement_receipts
    WHERE id = p_receipt_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    IF v_receipt.revision_number <> p_expected_revision THEN
        RAISE EXCEPTION 'acknowledgement receipt revision conflict'
            USING ERRCODE = '40001';
    END IF;

    IF v_receipt.voided_at IS NOT NULL THEN
        RAISE EXCEPTION 'voided receipts cannot accept transaction references'
            USING ERRCODE = '55000';
    END IF;

    SELECT *
    INTO v_transaction
    FROM public.transactions
    WHERE id = p_transaction_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE no_data_found;
    END IF;

    UPDATE public.transactions
    SET paid = p_paid
    WHERE id = p_transaction_id;

    IF v_transaction.person_id IS DISTINCT FROM v_receipt.payer_person_id THEN
        RAISE EXCEPTION 'transaction and receipt must have the same payer'
            USING ERRCODE = '22023';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.acknowledgement_receipt_transactions
        WHERE receipt_id = p_receipt_id
          AND transaction_id = p_transaction_id
    ) THEN
        RETURN jsonb_build_object(
            'transaction_id', p_transaction_id,
            'paid', p_paid,
            'receipt_id', p_receipt_id,
            'receipt_revision', v_receipt.revision_number
        );
    END IF;

    v_had_confirmation := (
        v_receipt.payer_confirmed_at IS NOT NULL
        OR v_receipt.receiver_confirmed_at IS NOT NULL
        OR v_receipt.completed_at IS NOT NULL
    );

    PERFORM public.ack_snapshot_receipt(
        p_receipt_id,
        'transaction reference added while marking paid',
        'receiver'
    );

    INSERT INTO public.acknowledgement_receipt_transactions (
        receipt_id,
        transaction_id,
        transaction_date_snapshot,
        description_snapshot,
        amount_snapshot
    )
    VALUES (
        p_receipt_id,
        p_transaction_id,
        v_transaction.date,
        v_transaction.description,
        v_transaction.amount
    );

    UPDATE public.acknowledgement_receipts
    SET
        revision_number = revision_number + 1,
        payer_confirmed_at = NULL,
        receiver_confirmed_at = NULL,
        completed_at = NULL
    WHERE id = p_receipt_id
    RETURNING * INTO v_receipt;

    INSERT INTO public.acknowledgement_receipt_events (
        receipt_id,
        event_type,
        actor_role,
        revision_number,
        details
    )
    VALUES (
        p_receipt_id,
        'transaction_linked',
        'receiver',
        v_receipt.revision_number,
        jsonb_build_object('transaction_id', p_transaction_id)
    );

    IF v_had_confirmation THEN
        INSERT INTO public.acknowledgement_receipt_events (
            receipt_id,
            event_type,
            actor_role,
            revision_number,
            details
        )
        VALUES (
            p_receipt_id,
            'confirmation_reset',
            'receiver',
            v_receipt.revision_number,
            '{"reason":"transaction_linked"}'::jsonb
        );
    END IF;

    RETURN jsonb_build_object(
        'transaction_id', p_transaction_id,
        'paid', p_paid,
        'receipt_id', p_receipt_id,
        'receipt_revision', v_receipt.revision_number
    );
END;
$$;

CREATE OR REPLACE VIEW public.acknowledgement_receipt_overview
WITH (security_invoker = true)
AS
SELECT
    receipt.*,
    CASE
        WHEN receipt.voided_at IS NOT NULL THEN 'voided'
        WHEN receipt.published_at IS NULL THEN 'draft'
        WHEN (
            receipt.completed_at IS NOT NULL
            AND receipt.payer_confirmed_at IS NOT NULL
            AND receipt.receiver_confirmed_at IS NOT NULL
        ) THEN 'completed'
        WHEN (
            receipt.payer_confirmed_at IS NULL
            AND receipt.receiver_confirmed_at IS NOT NULL
        ) THEN 'awaiting_payer'
        WHEN (
            receipt.payer_confirmed_at IS NOT NULL
            AND receipt.receiver_confirmed_at IS NULL
        ) THEN 'awaiting_receiver'
        ELSE 'awaiting_both'
    END AS status,
    (
        SELECT count(*)
        FROM public.acknowledgement_receipt_transactions receipt_transaction
        WHERE receipt_transaction.receipt_id = receipt.id
    ) AS transaction_count,
    (
        SELECT count(*)
        FROM public.acknowledgement_receipt_files receipt_file
        WHERE receipt_file.receipt_id = receipt.id
          AND receipt_file.removed_at IS NULL
    ) AS proof_count
FROM public.acknowledgement_receipts receipt;

ALTER TABLE public.payer_portal_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payer_portal_pin_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acknowledgement_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acknowledgement_receipt_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acknowledgement_receipt_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acknowledgement_receipt_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acknowledgement_receipt_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.payer_portal_access
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.payer_portal_pin_attempts
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.acknowledgement_receipts
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.acknowledgement_receipt_transactions
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.acknowledgement_receipt_files
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.acknowledgement_receipt_revisions
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.acknowledgement_receipt_events
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.acknowledgement_receipt_overview
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.ack_receipt_number_seq
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.payer_portal_pin_attempts_id_seq
    FROM PUBLIC, anon, authenticated;

REVOKE ALL ON FUNCTION public.ack_touch_updated_at()
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ack_reject_append_only()
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ack_enforce_active_file_limit()
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ack_snapshot_receipt(uuid, text, text)
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ack_create_receipt(
    uuid, text, numeric, text, date, text, uuid[]
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ack_update_receipt(
    uuid, integer, uuid, text, numeric, text, date, text, uuid[]
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ack_publish_receipt(uuid, integer)
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ack_confirm_receipt(uuid, integer, text)
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ack_void_receipt(uuid, integer, text)
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ack_register_file(
    uuid, integer, text, text, text, bigint, text
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ack_remove_file(
    uuid, integer, uuid, text
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ack_set_transaction_paid(
    uuid, boolean, uuid, integer
) FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT, UPDATE
    ON TABLE public.payer_portal_access
    TO service_role;
GRANT SELECT, INSERT, DELETE
    ON TABLE public.payer_portal_pin_attempts
    TO service_role;
GRANT SELECT, INSERT, UPDATE
    ON TABLE public.acknowledgement_receipts
    TO service_role;
GRANT SELECT, INSERT, DELETE
    ON TABLE public.acknowledgement_receipt_transactions
    TO service_role;
GRANT SELECT, INSERT, UPDATE
    ON TABLE public.acknowledgement_receipt_files
    TO service_role;
GRANT SELECT, INSERT
    ON TABLE
        public.acknowledgement_receipt_revisions,
        public.acknowledgement_receipt_events
    TO service_role;
GRANT SELECT ON TABLE public.acknowledgement_receipt_overview
    TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.ack_receipt_number_seq
    TO service_role;
GRANT USAGE, SELECT
    ON SEQUENCE public.payer_portal_pin_attempts_id_seq
    TO service_role;

GRANT EXECUTE ON FUNCTION public.ack_snapshot_receipt(uuid, text, text)
    TO service_role;
GRANT EXECUTE ON FUNCTION public.ack_create_receipt(
    uuid, text, numeric, text, date, text, uuid[]
) TO service_role;
GRANT EXECUTE ON FUNCTION public.ack_update_receipt(
    uuid, integer, uuid, text, numeric, text, date, text, uuid[]
) TO service_role;
GRANT EXECUTE ON FUNCTION public.ack_publish_receipt(uuid, integer)
    TO service_role;
GRANT EXECUTE ON FUNCTION public.ack_confirm_receipt(uuid, integer, text)
    TO service_role;
GRANT EXECUTE ON FUNCTION public.ack_void_receipt(uuid, integer, text)
    TO service_role;
GRANT EXECUTE ON FUNCTION public.ack_register_file(
    uuid, integer, text, text, text, bigint, text
) TO service_role;
GRANT EXECUTE ON FUNCTION public.ack_remove_file(
    uuid, integer, uuid, text
) TO service_role;
GRANT EXECUTE ON FUNCTION public.ack_set_transaction_paid(
    uuid, boolean, uuid, integer
) TO service_role;

COMMIT;
